# Template configuration réseau

# vm-db-master
network:
  version: 2
  ethernets:
    ens33:
    dhcp4: yes
    ens38:
      dhcp4: no
      addresses:
        - 192.168.56.20/24
	gateway4: 192.168.56.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4



# vm-db-master
network:
  version: 2
  ethernets:
    ens33:
    dhcp4: yes
    ens38:
      dhcp4: no
      addresses:
        - 192.168.56.21/24
	gateway4: 192.168.56.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4


# vm-lb
network:
  version: 2
  ethernets:
    dhcp4: yes
    ens33:
    ens38:
      dhcp4: no
      addresses:
        - 192.168.56.10/24
	gateway4: 192.168.56.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4


# vm-serv1
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: yes
    ens38:
      dhcp4: no
      addresses:
        - 192.168.56.11/24
	gateway4: 192.168.56.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4


# vm-serv2
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: yes
    ens38:
      dhcp4: no
      addresses:
        - 192.168.56.12/24
	gateway4: 192.168.56.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

# vm-firewall
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: yes
    ens34:
      dhcp4: no
      addresses:
        - 192.168.56.2/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4